openapi: 3.0.3
info:
  title: Device Controller
  description: Sync API Description
  version: "0.0.1"
tags:
  - name: device
    description: Device
servers:
  - url: http://localhost:80/
paths:
  /devices:
    get:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/offset'
      summary: Получить список всех устройств
      operationId: getAll
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginatedResult"
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: "#/components/schemas/Device"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
    post:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Зарегистрировать новое устройство
      operationId: create
      requestBody:
        description: Зарегистрировать новое устройство
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
        required: true
      responses:
        201:
          description: Устройство зарегистрировано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          $ref: '#/components/responses/BadRequestError'
        403:
          $ref: '#/components/responses/ForbiddenError'
  /devices/{id}:
    get:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Получить информацию об устройстве по его идентификатору
      operationId: get
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Информация об устройстве
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        403:
          $ref: '#/components/responses/ForbiddenError'
    delete:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Удалить устройство по его идентификатору
      operationId: delete
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Удалить устройство
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        403:
          $ref: '#/components/responses/ForbiddenError'
  /devices/{id}/action:
    post:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Передать команду устройству
      operationId: doAction
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        description: Описание команды
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        200:
          description: Команда принята
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        403:
          $ref: '#/components/responses/ForbiddenError'
  /devices/{id}/telemetry/latest:
    get:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Получить актуальные данные телеметрии устройства по его идентификатору
      operationId: getLatest
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TelemetryData"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
  /devices/{id}/telemetry:
    get:
      tags:
        - device
      security:
        - bearerAuth: [ ]
      summary: Получить всю данные телеметрии устройства по его идентификатору
      operationId: getAllData
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginatedResult"
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: "#/components/schemas/TelemetryData"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
components:
  responses:
    UnauthorizedError:
      description: Токен авторизации отсутствует или невалиден
    BadRequestError:
      description: Приложение не может обработать запрос
    ForbiddenError:
      description: Недостаточно прав для выполнения операции
    NotFoundError:
      description: Запрашиваемый объект не найден или не существует
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    pageNumber:
      in: query
      name: page
      schema:
        type: integer
        example: 0
    pageSize:
      in: query
      name: size
      schema:
        type: integer
        example: 10
        default: 10
    offset:
      in: query
      name: size
      schema:
        type: integer
        example: 10
        default: 0
    id:
      in: path
      name: id
      schema:
        type: integer
      required: true
      description: object id
  schemas:
    Action:
      type: object
      properties:
        command:
          type: string
          example: "Отключить"
    TelemetryData:
      type: object
      properties:
        id:
          type: number
          example: "123"
        device_id:
          type: number
          example: "456"
        value_name:
          type: number
          example: "Влажность воздуха, %"
        value:
          type: number
          example: "1"
        datetime:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00"
    Device:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: "ДТ-000"
          default: "ДТ-001"
        type:
          type: string
          example: "Датчик температуры"
          default: "Датчик температуры"
        serialNumber:
          type: string
          example: "0000-3421-2341-3123"
          default: "0000-0000-0000-0000"
        modelName:
          type: string
          example: "Внутриканальный анализатор"
          default: "Внутриканальный анализатор"
        manufacturer:
          type: string
          example: "Автоваз"
          default: "Автоваз"
    PaginatedResult:
      type: object
      properties:
        page: { type: number, example: 3 }
        pages: { type: number, example: 5 }
        size: { type: number, example: 20 }
        total: { type: number, example: 100 }
        results: { type: array, items: { } }

security:
  - bearerAuth: [ ]